# Project information
site_name: Design Guidelines
site_url: https://mydomain.org/mysite
site_author: Ssempijja Charles

# Copyright
copyright: Copyright &copy; 2025  Ssempijja Charles

# Repository
repo_name: Design-Docs
repo_url: https://github.com/Tiba-Inc/Design-Docs

theme:
  name: material
  locale: en
  color_mode: auto
  font:
    text: Roboto
    code: Roboto Mono

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.expand
    - navigation.indexes
    - navigation.top

# Page tree
nav:
  - Getting started: index.md
  - User flows: user-flows.md
  - Design tokens: design-tokens.md


# Extensions
markdown_extensions:
 # MermaidJS for diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      format: "YYYY-MM-DD"

  - git-committers:
      repository: Tiba-Inc/Design-Docs
      branch : main